name: anxiety_track
description: "A mental health app for tracking anxiety symptoms, created by people living with anxiety."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  
  # State management
  provider: ^6.1.1
  
  # Internationalization
  intl: ^0.20.2
  
  # UI components
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # CHANGE 1: Declare the dependency with a version number here.
  flutter_launcher_icons: ^0.13.1

# CHANGE 2: The configuration for the package goes here, at the top level.
# It should NOT be inside dev_dependencies.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  # CHANGE 3: You must declare your asset folder so Flutter can find the icon.
  assets:
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic